server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://inner.bitgamex.org:4042/higgs_network_wallet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: bitgame
    password: bitgame2018
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  session:
    store-type: redis
  redis:
    host: higgs-dev.bitgamex.org
    port: 6379
    password: redispass
mybatis:
  mapper-locations: classpath:com/bitgame/exchange/demo/dao/sqlmapper/*.xml
bmp:
  session:
    cookie:
      cookieName: LOGIN_SESSION
      domainName: www.test.com
      cookiePath: /
      useBase64Encoding: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true